# Generated by Django 5.2.17 on 2026-09-25 16:11

import accounts.models
import core.uploads
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="الاسم الكامل"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("profiles"),
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        default="نينوى", max_length=60, verbose_name="المحافظة"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        default="الموصل",
                        max_length=60,
                        verbose_name="المدينة",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=80,
                        verbose_name="الحي/المنطقة",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("citizen", "مواطن"),
                            ("volunteer", "متطوع"),
                            ("supervisor", "مشرف ميداني"),
                            ("admin", "مدير"),
                            ("super_admin", "مدير عام"),
                        ],
                        default="citizen",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="موثّق"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعّال")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="من فريق الإدارة"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الانضمام"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
