# Generated by Django 5.2.17 on 2026-09-25 16:11

import core.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("species", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "request_code",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="رقم الطلب"
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("home", "🏠 أمام البيت"),
                            ("shop", "🏪 أمام المحل"),
                            ("school", "🏫 مدرسة"),
                            ("university", "🎓 جامعة"),
                            ("hospital", "🏥 مستشفى"),
                            ("orchard", "🌾 بستان"),
                            ("village", "🏘️ قرية"),
                            ("institution", "🏢 مؤسسة"),
                            ("street", "🛣️ شارع"),
                            ("mosque", "🕌 جامع"),
                            ("public", "🌳 مكان عام"),
                            ("other", "➕ أخرى"),
                        ],
                        max_length=20,
                        verbose_name="مكان الزراعة",
                    ),
                ),
                (
                    "requested_tree_count",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="عدد الأشجار المطلوب",
                    ),
                ),
                (
                    "approved_tree_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(500)],
                        verbose_name="العدد الموافق عليه",
                    ),
                ),
                (
                    "watering_commitment",
                    models.BooleanField(default=True, verbose_name="الالتزام بالسقي"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="خط الطول",
                    ),
                ),
                (
                    "address_description",
                    models.CharField(max_length=250, verbose_name="وصف العنوان"),
                ),
                (
                    "governorate",
                    models.CharField(
                        default="نينوى", max_length=60, verbose_name="المحافظة"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        default="الموصل",
                        max_length=60,
                        verbose_name="المدينة / القضاء",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, db_index=True, max_length=80, verbose_name="الحي"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم التواصل"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "تم إرسال الطلب"),
                            ("under_review", "قيد المراجعة"),
                            ("approved", "تمت الموافقة"),
                            ("ready_for_distribution", "جاهز للاستلام"),
                            ("distributed", "تم الاستلام"),
                            ("planted", "تمت الزراعة"),
                            ("completed", "مكتمل"),
                            ("rejected", "مرفوض"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=30,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "distribution_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="موعد الاستلام"
                    ),
                ),
                (
                    "public_note",
                    models.TextField(blank=True, verbose_name="ملاحظة لصاحب الطلب"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات داخلية"),
                ),
                (
                    "assigned_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المشرف",
                    ),
                ),
                (
                    "preferred_species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="species.treespecies",
                        verbose_name="النوع المفضل",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="صاحب الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب شجرة",
                "verbose_name_plural": "طلبات الأشجار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreeRequestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.uploads.UploadTo("requests"),
                        verbose_name="صورة المكان",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tree_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tree_requests.treerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة الطلب",
                "verbose_name_plural": "صور الطلب",
            },
        ),
    ]
