# Generated by Django 5.2.17 on 2026-09-25 16:11

import core.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "report_code",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        unique=True,
                        verbose_name="رقم البلاغ",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tree_cutting", "🪓 قطع أشجار"),
                            ("fire", "🔥 حريق"),
                            ("illegal_hunting", "🏹 صيد جائر"),
                            ("waste", "🗑️ نفايات"),
                            ("green_area_destruction", "🏗️ تجريف مساحة خضراء"),
                            ("pollution", "💧 تلوث"),
                            ("wildlife_harm", "🐦 اعتداء على الحياة البرية"),
                            ("tree_damage", "🌳 شجرة متضررة"),
                            ("other", "➕ أخرى"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="نوع البلاغ",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="عنوان مختصر"
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="خط الطول",
                    ),
                ),
                (
                    "address_description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="وصف المكان"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        default="الموصل",
                        max_length=60,
                        verbose_name="المدينة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "تم الاستلام"),
                            ("under_review", "قيد المراجعة"),
                            ("verified", "تم التحقق"),
                            ("forwarded", "أُحيل للجهة المختصة"),
                            ("in_progress", "قيد المتابعة"),
                            ("resolved", "تمت المعالجة"),
                            ("rejected", "مرفوض"),
                            ("duplicate", "مكرر"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("normal", "عادية"),
                            ("high", "عالية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "public_note",
                    models.TextField(blank=True, verbose_name="ملاحظة للمبلّغ"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات داخلية"),
                ),
                (
                    "hide_reporter_identity",
                    models.BooleanField(
                        default=False, verbose_name="إخفاء هوية المبلّغ"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسند إلى",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المبلّغ",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلاغ بيئي",
                "verbose_name_plural": "البلاغات البيئية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalReportMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to=core.uploads.UploadTo("reports"), verbose_name="صورة"
                    ),
                ),
                ("media_type", models.CharField(default="image", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="reports.environmentalreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرفق البلاغ",
                "verbose_name_plural": "مرفقات البلاغ",
            },
        ),
    ]
