# Generated by Django 5.2.17 on 2026-09-25 16:11

import core.uploads
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="الاسم")),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                (
                    "icon",
                    models.CharField(default="🌿", max_length=8, verbose_name="رمز"),
                ),
                (
                    "is_legal",
                    models.BooleanField(
                        default=False, verbose_name="قسم قانوني (اعرف القانون)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "تصنيف",
                "verbose_name_plural": "تصنيفات المحتوى",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContributionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(default="🌱", max_length=8)),
                ("title", models.CharField(max_length=100, verbose_name="العنوان")),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="الوصف"),
                ),
                (
                    "amount_iqd",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="المبلغ التقريبي (د.ع)"
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "باب مساهمة",
                "verbose_name_plural": "أبواب المساهمة",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ContributionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الوسيلة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "account_information",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="معلومات الحساب"
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("contribution"),
                        verbose_name="رمز QR",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="التعليمات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعّال")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "وسيلة مساهمة",
                "verbose_name_plural": "وسائل المساهمة",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ContentArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=220, unique=True),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=300, verbose_name="الملخص"),
                ),
                ("body", models.TextField(verbose_name="المحتوى")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("articles"),
                        verbose_name="صورة",
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="المصدر")),
                (
                    "needs_legal_review",
                    models.BooleanField(
                        default=False, verbose_name="بحاجة لمراجعة قانونية رسمية"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ النشر"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منشور"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الكاتب",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="content.articlecategory",
                        verbose_name="التصنيف",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقال",
                "verbose_name_plural": "المقالات والتوعية",
                "ordering": ["-published_at"],
            },
        ),
    ]
