# Generated by Django 5.2.17 on 2026-09-25 16:11

import core.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("species", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantingSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم الموقع")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("forest", "غابة / مشروع تشجير"),
                            ("street", "شارع"),
                            ("neighborhood", "حي سكني"),
                            ("orchard", "بستان"),
                            ("school", "مدرسة / جامعة"),
                            ("hospital", "مستشفى"),
                            ("institution", "مؤسسة / دائرة"),
                            ("village", "قرية"),
                            ("public", "مكان عام"),
                        ],
                        default="street",
                        max_length=20,
                        verbose_name="نوع الموقع",
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        default="نينوى", max_length=60, verbose_name="المحافظة"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        default="الموصل",
                        max_length=60,
                        verbose_name="المدينة / القضاء",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=80,
                        verbose_name="الحي / المنطقة",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="خط الطول",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الجهة المنفذة"
                    ),
                ),
                (
                    "watering_entity",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="المسؤول عن السقي"
                    ),
                ),
                (
                    "planting_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاريخ الزراعة",
                    ),
                ),
                (
                    "total_trees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الأشجار المزروعة"
                    ),
                ),
                (
                    "alive_trees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الأشجار الحية"
                    ),
                ),
                (
                    "damaged_trees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الأشجار المتضررة"
                    ),
                ),
                (
                    "dead_trees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الأشجار الميتة"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("sites"),
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "before_image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("sites"),
                        verbose_name="صورة قبل",
                    ),
                ),
                (
                    "after_image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("sites"),
                        verbose_name="صورة بعد",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, verbose_name="رابط التوثيق (منشور)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعّال"),
                            ("needs_attention", "يحتاج متابعة"),
                            ("completed", "مكتمل"),
                            ("inactive", "متوقف"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز في الرئيسية"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sites",
                        to="species.treespecies",
                        verbose_name="الأنواع المزروعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "موقع تشجير",
                "verbose_name_plural": "مواقع التشجير",
                "ordering": ["-is_featured", "-planting_date"],
            },
        ),
        migrations.CreateModel(
            name="PlantingBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "batch_code",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        unique=True,
                        verbose_name="رمز الدفعة",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="العدد")),
                (
                    "planting_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاريخ الزراعة",
                    ),
                ),
                (
                    "responsible_entity",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الجهة المسؤولة"
                    ),
                ),
                (
                    "watering_entity",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="المسؤول عن السقي"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="species.treespecies",
                        verbose_name="النوع",
                    ),
                ),
                (
                    "planting_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="planting.plantingsite",
                        verbose_name="الموقع",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة زراعة",
                "verbose_name_plural": "دفعات الزراعة",
                "ordering": ["-planting_date"],
            },
        ),
    ]
