# Generated by Django 5.2.17 on 2026-09-25 16:11

import core.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="عنوان الحملة"),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("campaigns"),
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(max_length=150, verbose_name="المكان"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(db_index=True, verbose_name="موعد البدء"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="موعد الانتهاء"
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر موعد للتسجيل"
                    ),
                ),
                (
                    "target_tree_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الهدف (أشجار)"
                    ),
                ),
                (
                    "volunteers_needed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="المتطوعون المطلوبون"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الجهة المنظمة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("published", "التسجيل مفتوح"),
                            ("registration_closed", "التسجيل مغلق"),
                            ("active", "جارية الآن"),
                            ("completed", "منجزة"),
                            ("cancelled", "ملغاة"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=25,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "حملة",
                "verbose_name_plural": "الحملات",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CampaignParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "مسجّل"),
                            ("approved", "مقبول"),
                            ("attended", "حضر"),
                            ("absent", "غائب"),
                            ("completed", "أنجز"),
                            ("cancelled", "ألغى المشاركة"),
                        ],
                        default="registered",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "volunteer_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="ساعات التطوع",
                    ),
                ),
                (
                    "trees_planted",
                    models.PositiveIntegerField(default=0, verbose_name="أشجار زرعها"),
                ),
                ("notes", models.TextField(blank=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="campaigns.campaign",
                        verbose_name="الحملة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المتطوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشارك",
                "verbose_name_plural": "المشاركون",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "user"), name="unique_campaign_participant"
                    )
                ],
            },
        ),
    ]
