# Generated by Django 5.2.17 on 2026-09-25 16:11

import core.uploads
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planting", "0001_initial"),
        ("species", "0001_initial"),
        ("tree_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "tree_code",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        unique=True,
                        verbose_name="رمز الشجرة",
                    ),
                ),
                (
                    "qr_identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="اسم الشجرة (اختياري)"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="خط الطول",
                    ),
                ),
                (
                    "location_label",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الموقع (وصف)"
                    ),
                ),
                (
                    "planting_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="تاريخ الزراعة",
                    ),
                ),
                (
                    "caretaker_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="اسم الراعي (إن لم يكن مسجلاً)",
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الطول (سم)"
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("excellent", "ممتازة"),
                            ("good", "جيدة"),
                            ("needs_care", "تحتاج رعاية"),
                            ("damaged", "متضررة"),
                            ("dead", "ماتت"),
                        ],
                        db_index=True,
                        default="good",
                        max_length=20,
                        verbose_name="الحالة الصحية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "قائمة"),
                            ("dead", "ميتة"),
                            ("replaced", "تم استبدالها"),
                            ("removed", "أزيلت"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="الوضع",
                    ),
                ),
                (
                    "last_update_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر متابعة"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trees",
                        to="planting.plantingbatch",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "caretaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cared_trees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الراعي",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_trees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستفيد",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trees",
                        to="tree_requests.treerequest",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trees",
                        to="planting.plantingsite",
                        verbose_name="الموقع",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trees",
                        to="species.treespecies",
                        verbose_name="النوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "شجرة",
                "verbose_name_plural": "الأشجار",
                "ordering": ["-planting_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TreeUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("tree_updates"),
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الطول التقريبي (سم)"
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("excellent", "ممتازة"),
                            ("good", "جيدة"),
                            ("needs_care", "تحتاج رعاية"),
                            ("damaged", "متضررة"),
                            ("dead", "ماتت"),
                        ],
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "is_planting_day",
                    models.BooleanField(default=False, verbose_name="يوم الزراعة"),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="موثّق من الفريق"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="التاريخ",
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="trees.tree",
                        verbose_name="الشجرة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tree_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="وثّقه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحديث متابعة",
                "verbose_name_plural": "تحديثات المتابعة",
                "ordering": ["-created_at"],
            },
        ),
    ]
