# Generated by Django 5.2.17 on 2026-09-25 16:11

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreeSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "arabic_name",
                    models.CharField(max_length=100, verbose_name="الاسم العربي"),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم الإنكليزي"
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم العلمي"
                    ),
                ),
                (
                    "emoji",
                    models.CharField(default="🌳", max_length=8, verbose_name="رمز"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.uploads.UploadTo("species"),
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "heat_tolerance",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "ضعيف"),
                            (2, "مقبول"),
                            (3, "متوسط"),
                            (4, "جيد"),
                            (5, "ممتاز"),
                        ],
                        default=3,
                        verbose_name="تحمل الحرارة",
                    ),
                ),
                (
                    "drought_tolerance",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "ضعيف"),
                            (2, "مقبول"),
                            (3, "متوسط"),
                            (4, "جيد"),
                            (5, "ممتاز"),
                        ],
                        default=3,
                        verbose_name="تحمل الجفاف",
                    ),
                ),
                (
                    "water_requirement",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "قليل"), (2, "متوسط"), (3, "عالٍ")],
                        default=2,
                        verbose_name="احتياج الماء",
                    ),
                ),
                (
                    "growth_speed",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "ضعيف"),
                            (2, "مقبول"),
                            (3, "متوسط"),
                            (4, "جيد"),
                            (5, "ممتاز"),
                        ],
                        default=3,
                        verbose_name="سرعة النمو",
                    ),
                ),
                (
                    "shade_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "ضعيف"),
                            (2, "مقبول"),
                            (3, "متوسط"),
                            (4, "جيد"),
                            (5, "ممتاز"),
                        ],
                        default=3,
                        verbose_name="الظل",
                    ),
                ),
                (
                    "suitable_for_streets",
                    models.BooleanField(
                        default=False, verbose_name="مناسب للشوارع والأرصفة"
                    ),
                ),
                (
                    "suitable_for_gardens",
                    models.BooleanField(
                        default=False, verbose_name="مناسب للحدائق والبيوت"
                    ),
                ),
                (
                    "suitable_for_farms",
                    models.BooleanField(default=False, verbose_name="مناسب للبساتين"),
                ),
                (
                    "suitable_for_public_spaces",
                    models.BooleanField(
                        default=False, verbose_name="مناسب للغابات والأماكن العامة"
                    ),
                ),
                (
                    "bird_friendly",
                    models.BooleanField(default=False, verbose_name="مفيد للطيور"),
                ),
                ("fruitful", models.BooleanField(default=False, verbose_name="مثمر")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعّال")),
            ],
            options={
                "verbose_name": "نوع شجرة",
                "verbose_name_plural": "أنواع الأشجار",
                "ordering": ["arabic_name"],
            },
        ),
    ]
