# Generated by Django 5.2.17 on 2026-09-25 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="الإجراء")),
                (
                    "object_type",
                    models.CharField(max_length=100, verbose_name="نوع الكائن"),
                ),
                ("object_id", models.CharField(max_length=50, verbose_name="المعرف")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="تفاصيل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="التاريخ"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المنفّذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجل التدقيق",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(blank=True, verbose_name="النص")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("general", "عام"),
                            ("request", "طلب شجرة"),
                            ("tree", "متابعة شجرة"),
                            ("report", "بلاغ بيئي"),
                            ("campaign", "حملة"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "link",
                    models.CharField(blank=True, max_length=300, verbose_name="الرابط"),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                (
                    "related_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="التاريخ"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
    ]
